config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages
  validates :name, presence: true

  def message_display
    if messages.present?
      if messages.last.text.present?
        messages.last.text
      else
        "画像が投稿されています。"
      end
    else
      "メッセージはありません。"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  validates :text_or_image, presence: true
  private
  def text_or_image
    text.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, presence: true, uniqueness: true

  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

  def after_sign_out_path_for(resource)
    user_session_path
  end

   def after_sign_in_path_for(resource)
    root_path
   end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups
    @group = Group.find_by(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def update
    @group.update(group_params)
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

    private
    def group_params
      params.require(:group).permit(:name, user_ids: [])
    end

    def set_group
      @group = Group.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @group.messages
    respond_to do |format|
      format.html
      format.json { @new_message = @messages.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, flash: { notice: "送信しました"} }
        format.json
      end
    else
      flash.now[:alert] = "入力してください"
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

    private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def format_posted_time(time)
    time.to_s(:default)
  end
end

app/views/groups/_sidebar_groups.html.haml
= link_to group_messages_path(group) do
  %p.group-name
    = group.name
  %p.group-message
    = group.message_display

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", action: "/chat_groups/22", method: "post"}
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count}件のエラーが発生しました。
        %ul
          -@group.errors.full_messages.each do |message|
            %li
              =message
  = form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        .chat-group-form__label チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = f.text_field :name, class: "chat-group-form__input", type: "text", placeholder: "追加したいユーザー名を入力してください", id: "user-search-field", data: {id: "id"}
        #user-search-results
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label", id: "user-search-field-box"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix{ id: "chat-group-user-#{current_user.id}" }
            %input{ name: "chat_group[user_ids][]", type: "hidden", value: current_user.id }
            %p.chat-group-user__name= current_user.name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "更新する", class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.sidebar
  .header
    %p.header__username
      = current_user.name
    = link_to edit_user_registration_path do
      %i.header__btn-right.fa.fa-cog
    = link_to new_group_path do
      %i.header__btn-left.fa.fa-pencil-square-o
  .sidebar__groups
    .sidebar__groups__group
      = render partial: "sidebar_groups", collection: @groups, as: "group"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  %form#new_chat_group.new_chat_group{"accept-charset" => "UTF-8", action: "/chat_groups", method: "post"}
    - if @group.errors.any?
      .chat-group-form__errors
        %h2
          #{@group.errors.count}件のエラーが発生しました。
        %ul
          -@group.errors.full_messages.each do |message|
            %li
              =message
  = form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        .chat-group-form__label チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = f.text_field :name, class: "chat-group-form__input", type: "text", placeholder: "追加したいユーザー名を入力してください", id: "user-search-field", data: {id: "id"}
        #user-search-results
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label", id: "user-search-field-box"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix{ id: "chat-group-user-#{current_user.id}" }
            %input{ name: "chat_group[user_ids][]", type: "hidden", value: current_user.id }
            %p.chat-group-user__name= current_user.name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "登録する", class: "chat-group-form__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
  = render 'layouts/flash'
  = yield

app/views/messages/_contents__messages.html.haml
- @group.messages.each do |message|
  .message-format{'data-message-id': message.id}
    .message-top
      .message-top__name
        = message.user.name
      .message-top__date
        = format_posted_time(message.created_at)
    .message-bottom
      = message.text
      = image_tag message.image, size:'120x180' if message.image.present?

app/views/messages/_groups.html.haml
.sidebar__groups__group
- @groups.each do |group|
  %p.group-name
    = group.name
  %p.group-message
    まだメッセージはありません

app/views/messages/_sidebar__groups.html.haml
= link_to group_messages_path(group) do
  %p.group-name
    = group.name
  %p.group-message
    = group.message_display if group.messages.present?

app/views/messages/_sidebar_groups.html.haml
.sidebar__groups__group
  - @groups.each do |group|
    = link_to group_messages_path(group) do
      %p.group-name
        = group.name
      %p.group-message
        まだメッセージはありません

app/views/messages/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/messages/index.html.haml
.sidebar
  .header
    %p.header__username
      = current_user.name
    = link_to edit_user_registration_path do
      %i.header__btn-right.fa.fa-cog
    = link_to new_group_path do
      %i.header__btn-left.fa.fa-pencil-square-o
  .sidebar__groups
    .sidebar__groups__group
      = render partial: "sidebar__groups", collection: @groups, as: "group"
.contents
  .contents__header
    .name
      %p.groupname
        = @group.name
      %p.membername
        - @group.users.each do |member|
          = member.name
    = link_to edit_group_path(@group) do
      .box Edit
  .contents__messages
    = render partial: "contents__messages"
  .contents__form
    = form_for [@group, @message] do |f|
      .contents__form__input
        = f.text_field :text, class: "contents__form-field", placeholder: "type a message"
        %label.contents__form__input__btn
          .fa.fa-picture-o
          = f.file_field :image, class: "contents__form-image"
        = f.submit "send", class: "button"